// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCaiOGCC9K6MCpI_fJlOJ5sFBskCjdsVI',
    appId: '1:1067982286498:web:522ab1cb2ff9f2968eb1fb',
    messagingSenderId: '1067982286498',
    projectId: 'grenier-du-faso',
    authDomain: 'grenier-du-faso.firebaseapp.com',
    storageBucket: 'grenier-du-faso.appspot.com',
    measurementId: 'G-2GXBZ39GCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2nlpQs_inmTFISJ-80yxKyj6UwHvqDl4',
    appId: '1:1067982286498:android:bebcfd4d88d6625d8eb1fb',
    messagingSenderId: '1067982286498',
    projectId: 'grenier-du-faso',
    storageBucket: 'grenier-du-faso.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOGVazMeezv3GqjCKxS-KSQh6UBaQRQjo',
    appId: '1:1067982286498:ios:7e9c0072afa837ee8eb1fb',
    messagingSenderId: '1067982286498',
    projectId: 'grenier-du-faso',
    storageBucket: 'grenier-du-faso.appspot.com',
    iosClientId: '1067982286498-rniurukgdivv5u9fupo4vjd41872vrhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.grenierdufaso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOGVazMeezv3GqjCKxS-KSQh6UBaQRQjo',
    appId: '1:1067982286498:ios:a3c6adc8570719aa8eb1fb',
    messagingSenderId: '1067982286498',
    projectId: 'grenier-du-faso',
    storageBucket: 'grenier-du-faso.appspot.com',
    iosClientId: '1067982286498-rserhi65ooenbefduaqf0ktajj691l14.apps.googleusercontent.com',
    iosBundleId: 'com.example.grenierdufaso.RunnerTests',
  );
}
